
/*
 *    swutm note: This file will be REGENERATED on each build.
 */
package net.swutm.more_beautiful_plates.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.fml.event.lifecycle.FMLClientSetupEvent;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.eventbus.api.SubscribeEvent;
import net.minecraftforge.client.event.ColorHandlerEvent;
import net.minecraftforge.api.distmarker.Dist;

import net.minecraft.world.level.block.Block;

import net.swutm.more_beautiful_plates.block.WarpedStemPressurePlateBlock;
import net.swutm.more_beautiful_plates.block.WarpedNyliumPressurePlateBlock;
import net.swutm.more_beautiful_plates.block.SpruceLogPressurePlateBlock;
import net.swutm.more_beautiful_plates.block.SandPressurePlateBlock;
import net.swutm.more_beautiful_plates.block.RedSandPressurePlateBlock;
import net.swutm.more_beautiful_plates.block.PressurePlate99Block;
import net.swutm.more_beautiful_plates.block.PressurePlate98Block;
import net.swutm.more_beautiful_plates.block.PressurePlate97Block;
import net.swutm.more_beautiful_plates.block.PressurePlate96Block;
import net.swutm.more_beautiful_plates.block.PressurePlate95Block;
import net.swutm.more_beautiful_plates.block.PressurePlate94Block;
import net.swutm.more_beautiful_plates.block.PressurePlate93Block;
import net.swutm.more_beautiful_plates.block.PressurePlate92Block;
import net.swutm.more_beautiful_plates.block.PressurePlate91Block;
import net.swutm.more_beautiful_plates.block.PressurePlate90Block;
import net.swutm.more_beautiful_plates.block.PressurePlate89Block;
import net.swutm.more_beautiful_plates.block.PressurePlate88Block;
import net.swutm.more_beautiful_plates.block.PressurePlate87Block;
import net.swutm.more_beautiful_plates.block.PressurePlate86Block;
import net.swutm.more_beautiful_plates.block.PressurePlate85Block;
import net.swutm.more_beautiful_plates.block.PressurePlate84Block;
import net.swutm.more_beautiful_plates.block.PressurePlate83Block;
import net.swutm.more_beautiful_plates.block.PressurePlate82Block;
import net.swutm.more_beautiful_plates.block.PressurePlate81Block;
import net.swutm.more_beautiful_plates.block.PressurePlate80Block;
import net.swutm.more_beautiful_plates.block.PressurePlate79Block;
import net.swutm.more_beautiful_plates.block.PressurePlate78Block;
import net.swutm.more_beautiful_plates.block.PressurePlate77Block;
import net.swutm.more_beautiful_plates.block.PressurePlate76Block;
import net.swutm.more_beautiful_plates.block.PressurePlate75Block;
import net.swutm.more_beautiful_plates.block.PressurePlate74Block;
import net.swutm.more_beautiful_plates.block.PressurePlate73Block;
import net.swutm.more_beautiful_plates.block.PressurePlate72Block;
import net.swutm.more_beautiful_plates.block.PressurePlate71Block;
import net.swutm.more_beautiful_plates.block.PressurePlate70Block;
import net.swutm.more_beautiful_plates.block.PressurePlate69Block;
import net.swutm.more_beautiful_plates.block.PressurePlate68Block;
import net.swutm.more_beautiful_plates.block.PressurePlate67Block;
import net.swutm.more_beautiful_plates.block.PressurePlate65Block;
import net.swutm.more_beautiful_plates.block.PressurePlate64Block;
import net.swutm.more_beautiful_plates.block.PressurePlate63Block;
import net.swutm.more_beautiful_plates.block.PressurePlate62Block;
import net.swutm.more_beautiful_plates.block.PressurePlate61Block;
import net.swutm.more_beautiful_plates.block.PressurePlate60Block;
import net.swutm.more_beautiful_plates.block.PressurePlate59Block;
import net.swutm.more_beautiful_plates.block.PressurePlate58Block;
import net.swutm.more_beautiful_plates.block.PressurePlate57Block;
import net.swutm.more_beautiful_plates.block.PressurePlate56Block;
import net.swutm.more_beautiful_plates.block.PressurePlate55Block;
import net.swutm.more_beautiful_plates.block.PressurePlate54Block;
import net.swutm.more_beautiful_plates.block.PressurePlate53Block;
import net.swutm.more_beautiful_plates.block.PressurePlate52Block;
import net.swutm.more_beautiful_plates.block.PressurePlate51Block;
import net.swutm.more_beautiful_plates.block.PressurePlate50Block;
import net.swutm.more_beautiful_plates.block.PressurePlate49Block;
import net.swutm.more_beautiful_plates.block.PressurePlate48Block;
import net.swutm.more_beautiful_plates.block.PressurePlate47Block;
import net.swutm.more_beautiful_plates.block.PressurePlate46Block;
import net.swutm.more_beautiful_plates.block.PressurePlate45Block;
import net.swutm.more_beautiful_plates.block.PressurePlate44Block;
import net.swutm.more_beautiful_plates.block.PressurePlate43Block;
import net.swutm.more_beautiful_plates.block.PressurePlate42Block;
import net.swutm.more_beautiful_plates.block.PressurePlate41Block;
import net.swutm.more_beautiful_plates.block.PressurePlate40Block;
import net.swutm.more_beautiful_plates.block.PressurePlate39Block;
import net.swutm.more_beautiful_plates.block.PressurePlate38Block;
import net.swutm.more_beautiful_plates.block.PressurePlate37Block;
import net.swutm.more_beautiful_plates.block.PressurePlate36Block;
import net.swutm.more_beautiful_plates.block.PressurePlate35Block;
import net.swutm.more_beautiful_plates.block.PressurePlate34Block;
import net.swutm.more_beautiful_plates.block.PressurePlate33Block;
import net.swutm.more_beautiful_plates.block.PressurePlate32Block;
import net.swutm.more_beautiful_plates.block.PressurePlate31Block;
import net.swutm.more_beautiful_plates.block.PressurePlate30Block;
import net.swutm.more_beautiful_plates.block.PressurePlate29Block;
import net.swutm.more_beautiful_plates.block.PressurePlate28Block;
import net.swutm.more_beautiful_plates.block.PressurePlate27Block;
import net.swutm.more_beautiful_plates.block.PressurePlate26Block;
import net.swutm.more_beautiful_plates.block.PressurePlate268Block;
import net.swutm.more_beautiful_plates.block.PressurePlate267Block;
import net.swutm.more_beautiful_plates.block.PressurePlate266Block;
import net.swutm.more_beautiful_plates.block.PressurePlate265Block;
import net.swutm.more_beautiful_plates.block.PressurePlate264Block;
import net.swutm.more_beautiful_plates.block.PressurePlate263Block;
import net.swutm.more_beautiful_plates.block.PressurePlate262Block;
import net.swutm.more_beautiful_plates.block.PressurePlate261Block;
import net.swutm.more_beautiful_plates.block.PressurePlate260Block;
import net.swutm.more_beautiful_plates.block.PressurePlate25Block;
import net.swutm.more_beautiful_plates.block.PressurePlate259Block;
import net.swutm.more_beautiful_plates.block.PressurePlate258Block;
import net.swutm.more_beautiful_plates.block.PressurePlate257Block;
import net.swutm.more_beautiful_plates.block.PressurePlate256Block;
import net.swutm.more_beautiful_plates.block.PressurePlate255Block;
import net.swutm.more_beautiful_plates.block.PressurePlate254Block;
import net.swutm.more_beautiful_plates.block.PressurePlate253Block;
import net.swutm.more_beautiful_plates.block.PressurePlate252Block;
import net.swutm.more_beautiful_plates.block.PressurePlate251Block;
import net.swutm.more_beautiful_plates.block.PressurePlate250Block;
import net.swutm.more_beautiful_plates.block.PressurePlate24Block;
import net.swutm.more_beautiful_plates.block.PressurePlate249Block;
import net.swutm.more_beautiful_plates.block.PressurePlate248Block;
import net.swutm.more_beautiful_plates.block.PressurePlate247Block;
import net.swutm.more_beautiful_plates.block.PressurePlate246Block;
import net.swutm.more_beautiful_plates.block.PressurePlate245Block;
import net.swutm.more_beautiful_plates.block.PressurePlate244Block;
import net.swutm.more_beautiful_plates.block.PressurePlate243Block;
import net.swutm.more_beautiful_plates.block.PressurePlate242Block;
import net.swutm.more_beautiful_plates.block.PressurePlate241Block;
import net.swutm.more_beautiful_plates.block.PressurePlate240Block;
import net.swutm.more_beautiful_plates.block.PressurePlate23Block;
import net.swutm.more_beautiful_plates.block.PressurePlate239Block;
import net.swutm.more_beautiful_plates.block.PressurePlate238Block;
import net.swutm.more_beautiful_plates.block.PressurePlate237Block;
import net.swutm.more_beautiful_plates.block.PressurePlate236Block;
import net.swutm.more_beautiful_plates.block.PressurePlate235Block;
import net.swutm.more_beautiful_plates.block.PressurePlate234Block;
import net.swutm.more_beautiful_plates.block.PressurePlate233Block;
import net.swutm.more_beautiful_plates.block.PressurePlate232Block;
import net.swutm.more_beautiful_plates.block.PressurePlate231Block;
import net.swutm.more_beautiful_plates.block.PressurePlate230Block;
import net.swutm.more_beautiful_plates.block.PressurePlate22Block;
import net.swutm.more_beautiful_plates.block.PressurePlate229Block;
import net.swutm.more_beautiful_plates.block.PressurePlate228Block;
import net.swutm.more_beautiful_plates.block.PressurePlate227Block;
import net.swutm.more_beautiful_plates.block.PressurePlate226Block;
import net.swutm.more_beautiful_plates.block.PressurePlate225Block;
import net.swutm.more_beautiful_plates.block.PressurePlate224Block;
import net.swutm.more_beautiful_plates.block.PressurePlate223Block;
import net.swutm.more_beautiful_plates.block.PressurePlate222Block;
import net.swutm.more_beautiful_plates.block.PressurePlate221Block;
import net.swutm.more_beautiful_plates.block.PressurePlate220Block;
import net.swutm.more_beautiful_plates.block.PressurePlate21Block;
import net.swutm.more_beautiful_plates.block.PressurePlate219Block;
import net.swutm.more_beautiful_plates.block.PressurePlate218Block;
import net.swutm.more_beautiful_plates.block.PressurePlate217Block;
import net.swutm.more_beautiful_plates.block.PressurePlate216Block;
import net.swutm.more_beautiful_plates.block.PressurePlate215Block;
import net.swutm.more_beautiful_plates.block.PressurePlate214Block;
import net.swutm.more_beautiful_plates.block.PressurePlate213Block;
import net.swutm.more_beautiful_plates.block.PressurePlate212Block;
import net.swutm.more_beautiful_plates.block.PressurePlate211Block;
import net.swutm.more_beautiful_plates.block.PressurePlate210Block;
import net.swutm.more_beautiful_plates.block.PressurePlate20Block;
import net.swutm.more_beautiful_plates.block.PressurePlate209Block;
import net.swutm.more_beautiful_plates.block.PressurePlate208Block;
import net.swutm.more_beautiful_plates.block.PressurePlate207Block;
import net.swutm.more_beautiful_plates.block.PressurePlate206Block;
import net.swutm.more_beautiful_plates.block.PressurePlate205Block;
import net.swutm.more_beautiful_plates.block.PressurePlate204Block;
import net.swutm.more_beautiful_plates.block.PressurePlate203Block;
import net.swutm.more_beautiful_plates.block.PressurePlate202Block;
import net.swutm.more_beautiful_plates.block.PressurePlate201Block;
import net.swutm.more_beautiful_plates.block.PressurePlate200Block;
import net.swutm.more_beautiful_plates.block.PressurePlate19Block;
import net.swutm.more_beautiful_plates.block.PressurePlate199Block;
import net.swutm.more_beautiful_plates.block.PressurePlate198Block;
import net.swutm.more_beautiful_plates.block.PressurePlate197Block;
import net.swutm.more_beautiful_plates.block.PressurePlate196Block;
import net.swutm.more_beautiful_plates.block.PressurePlate195Block;
import net.swutm.more_beautiful_plates.block.PressurePlate194Block;
import net.swutm.more_beautiful_plates.block.PressurePlate193Block;
import net.swutm.more_beautiful_plates.block.PressurePlate192Block;
import net.swutm.more_beautiful_plates.block.PressurePlate191Block;
import net.swutm.more_beautiful_plates.block.PressurePlate190Block;
import net.swutm.more_beautiful_plates.block.PressurePlate18Block;
import net.swutm.more_beautiful_plates.block.PressurePlate189Block;
import net.swutm.more_beautiful_plates.block.PressurePlate188Block;
import net.swutm.more_beautiful_plates.block.PressurePlate187Block;
import net.swutm.more_beautiful_plates.block.PressurePlate186Block;
import net.swutm.more_beautiful_plates.block.PressurePlate185Block;
import net.swutm.more_beautiful_plates.block.PressurePlate184Block;
import net.swutm.more_beautiful_plates.block.PressurePlate183Block;
import net.swutm.more_beautiful_plates.block.PressurePlate182Block;
import net.swutm.more_beautiful_plates.block.PressurePlate181Block;
import net.swutm.more_beautiful_plates.block.PressurePlate180Block;
import net.swutm.more_beautiful_plates.block.PressurePlate179Block;
import net.swutm.more_beautiful_plates.block.PressurePlate178Block;
import net.swutm.more_beautiful_plates.block.PressurePlate177Block;
import net.swutm.more_beautiful_plates.block.PressurePlate176Block;
import net.swutm.more_beautiful_plates.block.PressurePlate175Block;
import net.swutm.more_beautiful_plates.block.PressurePlate174Block;
import net.swutm.more_beautiful_plates.block.PressurePlate173Block;
import net.swutm.more_beautiful_plates.block.PressurePlate172Block;
import net.swutm.more_beautiful_plates.block.PressurePlate171Block;
import net.swutm.more_beautiful_plates.block.PressurePlate170Block;
import net.swutm.more_beautiful_plates.block.PressurePlate169Block;
import net.swutm.more_beautiful_plates.block.PressurePlate168Block;
import net.swutm.more_beautiful_plates.block.PressurePlate167Block;
import net.swutm.more_beautiful_plates.block.PressurePlate165Block;
import net.swutm.more_beautiful_plates.block.PressurePlate164Block;
import net.swutm.more_beautiful_plates.block.PressurePlate163Block;
import net.swutm.more_beautiful_plates.block.PressurePlate161Block;
import net.swutm.more_beautiful_plates.block.PressurePlate160Block;
import net.swutm.more_beautiful_plates.block.PressurePlate159Block;
import net.swutm.more_beautiful_plates.block.PressurePlate158Block;
import net.swutm.more_beautiful_plates.block.PressurePlate157Block;
import net.swutm.more_beautiful_plates.block.PressurePlate156Block;
import net.swutm.more_beautiful_plates.block.PressurePlate155Block;
import net.swutm.more_beautiful_plates.block.PressurePlate154Block;
import net.swutm.more_beautiful_plates.block.PressurePlate153Block;
import net.swutm.more_beautiful_plates.block.PressurePlate152Block;
import net.swutm.more_beautiful_plates.block.PressurePlate151Block;
import net.swutm.more_beautiful_plates.block.PressurePlate150Block;
import net.swutm.more_beautiful_plates.block.PressurePlate149Block;
import net.swutm.more_beautiful_plates.block.PressurePlate148Block;
import net.swutm.more_beautiful_plates.block.PressurePlate147Block;
import net.swutm.more_beautiful_plates.block.PressurePlate146Block;
import net.swutm.more_beautiful_plates.block.PressurePlate145Block;
import net.swutm.more_beautiful_plates.block.PressurePlate144Block;
import net.swutm.more_beautiful_plates.block.PressurePlate143Block;
import net.swutm.more_beautiful_plates.block.PressurePlate142Block;
import net.swutm.more_beautiful_plates.block.PressurePlate141Block;
import net.swutm.more_beautiful_plates.block.PressurePlate140Block;
import net.swutm.more_beautiful_plates.block.PressurePlate139Block;
import net.swutm.more_beautiful_plates.block.PressurePlate138Block;
import net.swutm.more_beautiful_plates.block.PressurePlate137Block;
import net.swutm.more_beautiful_plates.block.PressurePlate136Block;
import net.swutm.more_beautiful_plates.block.PressurePlate135Block;
import net.swutm.more_beautiful_plates.block.PressurePlate134Block;
import net.swutm.more_beautiful_plates.block.PressurePlate133Block;
import net.swutm.more_beautiful_plates.block.PressurePlate132Block;
import net.swutm.more_beautiful_plates.block.PressurePlate131Block;
import net.swutm.more_beautiful_plates.block.PressurePlate130Block;
import net.swutm.more_beautiful_plates.block.PressurePlate129Block;
import net.swutm.more_beautiful_plates.block.PressurePlate128Block;
import net.swutm.more_beautiful_plates.block.PressurePlate127Block;
import net.swutm.more_beautiful_plates.block.PressurePlate126Block;
import net.swutm.more_beautiful_plates.block.PressurePlate125Block;
import net.swutm.more_beautiful_plates.block.PressurePlate124Block;
import net.swutm.more_beautiful_plates.block.PressurePlate123Block;
import net.swutm.more_beautiful_plates.block.PressurePlate122Block;
import net.swutm.more_beautiful_plates.block.PressurePlate121Block;
import net.swutm.more_beautiful_plates.block.PressurePlate120Block;
import net.swutm.more_beautiful_plates.block.PressurePlate119Block;
import net.swutm.more_beautiful_plates.block.PressurePlate118Block;
import net.swutm.more_beautiful_plates.block.PressurePlate117Block;
import net.swutm.more_beautiful_plates.block.PressurePlate116Block;
import net.swutm.more_beautiful_plates.block.PressurePlate115Block;
import net.swutm.more_beautiful_plates.block.PressurePlate114Block;
import net.swutm.more_beautiful_plates.block.PressurePlate113Block;
import net.swutm.more_beautiful_plates.block.PressurePlate112Block;
import net.swutm.more_beautiful_plates.block.PressurePlate111Block;
import net.swutm.more_beautiful_plates.block.PressurePlate110Block;
import net.swutm.more_beautiful_plates.block.PressurePlate109Block;
import net.swutm.more_beautiful_plates.block.PressurePlate108Block;
import net.swutm.more_beautiful_plates.block.PressurePlate107Block;
import net.swutm.more_beautiful_plates.block.PressurePlate106Block;
import net.swutm.more_beautiful_plates.block.PressurePlate105Block;
import net.swutm.more_beautiful_plates.block.PressurePlate104Block;
import net.swutm.more_beautiful_plates.block.PressurePlate103Block;
import net.swutm.more_beautiful_plates.block.PressurePlate102Block;
import net.swutm.more_beautiful_plates.block.PressurePlate101Block;
import net.swutm.more_beautiful_plates.block.PressurePlate100Block;
import net.swutm.more_beautiful_plates.block.PolishedGranitePressurePlateBlock;
import net.swutm.more_beautiful_plates.block.PolishedDioritePressurePlateBlock;
import net.swutm.more_beautiful_plates.block.PolishedAndesitePressurePlateBlock;
import net.swutm.more_beautiful_plates.block.PodzolPressurePlateBlock;
import net.swutm.more_beautiful_plates.block.OakLogPressurePlateBlock;
import net.swutm.more_beautiful_plates.block.NetherGoldOrePressurePlateBlock;
import net.swutm.more_beautiful_plates.block.JungleLogPressurePlateBlock;
import net.swutm.more_beautiful_plates.block.IronOrePressurePlateBlock;
import net.swutm.more_beautiful_plates.block.GravelPressurePlateBlock;
import net.swutm.more_beautiful_plates.block.GrassPressurePlateBlock;
import net.swutm.more_beautiful_plates.block.GranitePressurePlateBlock;
import net.swutm.more_beautiful_plates.block.GoldOrePressurePlateBlock;
import net.swutm.more_beautiful_plates.block.DirtPressurePlateBlock;
import net.swutm.more_beautiful_plates.block.DioritePressurePlateBlock;
import net.swutm.more_beautiful_plates.block.DarkOakLogPressurePlateBlock;
import net.swutm.more_beautiful_plates.block.CrimsonStemPressurePlateBlock;
import net.swutm.more_beautiful_plates.block.CrimsonNyliumPressurePlateBlock;
import net.swutm.more_beautiful_plates.block.CobblestonePressurePlateBlock;
import net.swutm.more_beautiful_plates.block.CoarseDirtPressurePlateBlock;
import net.swutm.more_beautiful_plates.block.CoalOrePressurePlateBlock;
import net.swutm.more_beautiful_plates.block.BirchLogPressurePlateBlock;
import net.swutm.more_beautiful_plates.block.BedrockPressurePlateBlock;
import net.swutm.more_beautiful_plates.block.AndesitePressurePlateBlock;
import net.swutm.more_beautiful_plates.block.AcaciaLogPressurePlateBlock;
import net.swutm.more_beautiful_plates.more_beautiful_plates;
public class MoreBeautifulPlatesModBlocks {
	public static final DeferredRegister<Block> REGISTRY = DeferredRegister.create(ForgeRegistries.BLOCKS, more_beautiful_plates.MOD_ID);
	public static final RegistryObject<Block> GRASS_PRESSURE_PLATE = REGISTRY.register("grass_pressure_plate", GrassPressurePlateBlock::new);
	public static final RegistryObject<Block> DIRT_PRESSURE_PLATE = REGISTRY.register("dirt_pressure_plate", DirtPressurePlateBlock::new);
	public static final RegistryObject<Block> COBBLESTONE_PRESSURE_PLATE = REGISTRY.register("cobblestone_pressure_plate",
			CobblestonePressurePlateBlock::new);
	public static final RegistryObject<Block> GRANITE_PRESSURE_PLATE = REGISTRY.register("granite_pressure_plate",
			GranitePressurePlateBlock::new);
	public static final RegistryObject<Block> POLISHED_GRANITE_PRESSURE_PLATE = REGISTRY.register("polished_granite_pressure_plate",
			PolishedGranitePressurePlateBlock::new);
	public static final RegistryObject<Block> DIORITE_PRESSURE_PLATE = REGISTRY.register("diorite_pressure_plate",
			DioritePressurePlateBlock::new);
	public static final RegistryObject<Block> POLISHED_DIORITE_PRESSURE_PLATE = REGISTRY.register("polished_diorite_pressure_plate",
			PolishedDioritePressurePlateBlock::new);
	public static final RegistryObject<Block> ANDESITE_PRESSURE_PLATE = REGISTRY.register("andesite_pressure_plate",
			AndesitePressurePlateBlock::new);
	public static final RegistryObject<Block> POLISHED_ANDESITE_PRESSURE_PLATE = REGISTRY.register("polished_andesite_pressure_plate",
			PolishedAndesitePressurePlateBlock::new);
	public static final RegistryObject<Block> COARSE_DIRT_PRESSURE_PLATE = REGISTRY.register("coarse_dirt_pressure_plate",
			CoarseDirtPressurePlateBlock::new);
	public static final RegistryObject<Block> PODZOL_PRESSURE_PLATE = REGISTRY.register("podzol_pressure_plate",
			PodzolPressurePlateBlock::new);
	public static final RegistryObject<Block> CRIMSON_NYLIUM_PRESSURE_PLATE = REGISTRY.register("crimson_nylium_pressure_plate",
			CrimsonNyliumPressurePlateBlock::new);
	public static final RegistryObject<Block> WARPED_NYLIUM_PRESSURE_PLATE = REGISTRY.register("warped_nylium_pressure_plate",
			WarpedNyliumPressurePlateBlock::new);
	public static final RegistryObject<Block> BEDROCK_PRESSURE_PLATE = REGISTRY.register("bedrock_pressure_plate",
			BedrockPressurePlateBlock::new);
	public static final RegistryObject<Block> SAND_PRESSURE_PLATE = REGISTRY.register("sand_pressure_plate", SandPressurePlateBlock::new);
	public static final RegistryObject<Block> RED_SAND_PRESSURE_PLATE = REGISTRY.register("red_sand_pressure_plate",
			RedSandPressurePlateBlock::new);
	public static final RegistryObject<Block> GRAVEL_PRESSURE_PLATE = REGISTRY.register("gravel_pressure_plate",
			GravelPressurePlateBlock::new);
	public static final RegistryObject<Block> GOLD_ORE_PRESSURE_PLATE = REGISTRY.register("gold_ore_pressure_plate",
			GoldOrePressurePlateBlock::new);
	public static final RegistryObject<Block> IRON_ORE_PRESSURE_PLATE = REGISTRY.register("iron_ore_pressure_plate",
			IronOrePressurePlateBlock::new);
	public static final RegistryObject<Block> COAL_ORE_PRESSURE_PLATE = REGISTRY.register("coal_ore_pressure_plate",
			CoalOrePressurePlateBlock::new);
	public static final RegistryObject<Block> NETHER_GOLD_ORE_PRESSURE_PLATE = REGISTRY.register("nether_gold_ore_pressure_plate",
			NetherGoldOrePressurePlateBlock::new);
	public static final RegistryObject<Block> OAK_LOG_PRESSURE_PLATE = REGISTRY.register("oak_log_pressure_plate",
			OakLogPressurePlateBlock::new);
	public static final RegistryObject<Block> SPRUCE_LOG_PRESSURE_PLATE = REGISTRY.register("spruce_log_pressure_plate",
			SpruceLogPressurePlateBlock::new);
	public static final RegistryObject<Block> BIRCH_LOG_PRESSURE_PLATE = REGISTRY.register("birch_log_pressure_plate",
			BirchLogPressurePlateBlock::new);
	public static final RegistryObject<Block> JUNGLE_LOG_PRESSURE_PLATE = REGISTRY.register("jungle_log_pressure_plate",
			JungleLogPressurePlateBlock::new);
	public static final RegistryObject<Block> ACACIA_LOG_PRESSURE_PLATE = REGISTRY.register("acacia_log_pressure_plate",
			AcaciaLogPressurePlateBlock::new);
	public static final RegistryObject<Block> DARK_OAK_LOG_PRESSURE_PLATE = REGISTRY.register("dark_oak_log_pressure_plate",
			DarkOakLogPressurePlateBlock::new);
	public static final RegistryObject<Block> CRIMSON_STEM_PRESSURE_PLATE = REGISTRY.register("crimson_stem_pressure_plate",
			CrimsonStemPressurePlateBlock::new);
	public static final RegistryObject<Block> WARPED_STEM_PRESSURE_PLATE = REGISTRY.register("warped_stem_pressure_plate",
			WarpedStemPressurePlateBlock::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_18 = REGISTRY.register("pressure_plate_18", PressurePlate18Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_19 = REGISTRY.register("pressure_plate_19", PressurePlate19Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_20 = REGISTRY.register("pressure_plate_20", PressurePlate20Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_21 = REGISTRY.register("pressure_plate_21", PressurePlate21Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_22 = REGISTRY.register("pressure_plate_22", PressurePlate22Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_23 = REGISTRY.register("pressure_plate_23", PressurePlate23Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_24 = REGISTRY.register("pressure_plate_24", PressurePlate24Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_25 = REGISTRY.register("pressure_plate_25", PressurePlate25Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_26 = REGISTRY.register("pressure_plate_26", PressurePlate26Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_27 = REGISTRY.register("pressure_plate_27", PressurePlate27Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_28 = REGISTRY.register("pressure_plate_28", PressurePlate28Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_29 = REGISTRY.register("pressure_plate_29", PressurePlate29Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_30 = REGISTRY.register("pressure_plate_30", PressurePlate30Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_31 = REGISTRY.register("pressure_plate_31", PressurePlate31Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_32 = REGISTRY.register("pressure_plate_32", PressurePlate32Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_33 = REGISTRY.register("pressure_plate_33", PressurePlate33Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_34 = REGISTRY.register("pressure_plate_34", PressurePlate34Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_35 = REGISTRY.register("pressure_plate_35", PressurePlate35Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_36 = REGISTRY.register("pressure_plate_36", PressurePlate36Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_37 = REGISTRY.register("pressure_plate_37", PressurePlate37Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_38 = REGISTRY.register("pressure_plate_38", PressurePlate38Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_39 = REGISTRY.register("pressure_plate_39", PressurePlate39Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_40 = REGISTRY.register("pressure_plate_40", PressurePlate40Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_41 = REGISTRY.register("pressure_plate_41", PressurePlate41Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_42 = REGISTRY.register("pressure_plate_42", PressurePlate42Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_43 = REGISTRY.register("pressure_plate_43", PressurePlate43Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_44 = REGISTRY.register("pressure_plate_44", PressurePlate44Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_45 = REGISTRY.register("pressure_plate_45", PressurePlate45Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_46 = REGISTRY.register("pressure_plate_46", PressurePlate46Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_47 = REGISTRY.register("pressure_plate_47", PressurePlate47Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_48 = REGISTRY.register("pressure_plate_48", PressurePlate48Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_49 = REGISTRY.register("pressure_plate_49", PressurePlate49Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_50 = REGISTRY.register("pressure_plate_50", PressurePlate50Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_51 = REGISTRY.register("pressure_plate_51", PressurePlate51Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_52 = REGISTRY.register("pressure_plate_52", PressurePlate52Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_53 = REGISTRY.register("pressure_plate_53", PressurePlate53Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_54 = REGISTRY.register("pressure_plate_54", PressurePlate54Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_55 = REGISTRY.register("pressure_plate_55", PressurePlate55Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_56 = REGISTRY.register("pressure_plate_56", PressurePlate56Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_57 = REGISTRY.register("pressure_plate_57", PressurePlate57Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_58 = REGISTRY.register("pressure_plate_58", PressurePlate58Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_59 = REGISTRY.register("pressure_plate_59", PressurePlate59Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_60 = REGISTRY.register("pressure_plate_60", PressurePlate60Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_61 = REGISTRY.register("pressure_plate_61", PressurePlate61Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_62 = REGISTRY.register("pressure_plate_62", PressurePlate62Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_63 = REGISTRY.register("pressure_plate_63", PressurePlate63Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_64 = REGISTRY.register("pressure_plate_64", PressurePlate64Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_65 = REGISTRY.register("pressure_plate_65", PressurePlate65Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_67 = REGISTRY.register("pressure_plate_67", PressurePlate67Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_68 = REGISTRY.register("pressure_plate_68", PressurePlate68Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_69 = REGISTRY.register("pressure_plate_69", PressurePlate69Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_70 = REGISTRY.register("pressure_plate_70", PressurePlate70Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_71 = REGISTRY.register("pressure_plate_71", PressurePlate71Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_72 = REGISTRY.register("pressure_plate_72", PressurePlate72Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_73 = REGISTRY.register("pressure_plate_73", PressurePlate73Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_74 = REGISTRY.register("pressure_plate_74", PressurePlate74Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_75 = REGISTRY.register("pressure_plate_75", PressurePlate75Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_76 = REGISTRY.register("pressure_plate_76", PressurePlate76Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_77 = REGISTRY.register("pressure_plate_77", PressurePlate77Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_78 = REGISTRY.register("pressure_plate_78", PressurePlate78Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_79 = REGISTRY.register("pressure_plate_79", PressurePlate79Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_80 = REGISTRY.register("pressure_plate_80", PressurePlate80Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_81 = REGISTRY.register("pressure_plate_81", PressurePlate81Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_82 = REGISTRY.register("pressure_plate_82", PressurePlate82Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_83 = REGISTRY.register("pressure_plate_83", PressurePlate83Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_84 = REGISTRY.register("pressure_plate_84", PressurePlate84Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_85 = REGISTRY.register("pressure_plate_85", PressurePlate85Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_86 = REGISTRY.register("pressure_plate_86", PressurePlate86Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_87 = REGISTRY.register("pressure_plate_87", PressurePlate87Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_88 = REGISTRY.register("pressure_plate_88", PressurePlate88Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_89 = REGISTRY.register("pressure_plate_89", PressurePlate89Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_90 = REGISTRY.register("pressure_plate_90", PressurePlate90Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_91 = REGISTRY.register("pressure_plate_91", PressurePlate91Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_92 = REGISTRY.register("pressure_plate_92", PressurePlate92Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_93 = REGISTRY.register("pressure_plate_93", PressurePlate93Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_94 = REGISTRY.register("pressure_plate_94", PressurePlate94Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_95 = REGISTRY.register("pressure_plate_95", PressurePlate95Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_96 = REGISTRY.register("pressure_plate_96", PressurePlate96Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_97 = REGISTRY.register("pressure_plate_97", PressurePlate97Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_98 = REGISTRY.register("pressure_plate_98", PressurePlate98Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_99 = REGISTRY.register("pressure_plate_99", PressurePlate99Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_100 = REGISTRY.register("pressure_plate_100", PressurePlate100Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_101 = REGISTRY.register("pressure_plate_101", PressurePlate101Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_102 = REGISTRY.register("pressure_plate_102", PressurePlate102Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_103 = REGISTRY.register("pressure_plate_103", PressurePlate103Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_104 = REGISTRY.register("pressure_plate_104", PressurePlate104Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_105 = REGISTRY.register("pressure_plate_105", PressurePlate105Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_106 = REGISTRY.register("pressure_plate_106", PressurePlate106Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_107 = REGISTRY.register("pressure_plate_107", PressurePlate107Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_108 = REGISTRY.register("pressure_plate_108", PressurePlate108Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_109 = REGISTRY.register("pressure_plate_109", PressurePlate109Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_110 = REGISTRY.register("pressure_plate_110", PressurePlate110Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_111 = REGISTRY.register("pressure_plate_111", PressurePlate111Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_112 = REGISTRY.register("pressure_plate_112", PressurePlate112Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_113 = REGISTRY.register("pressure_plate_113", PressurePlate113Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_114 = REGISTRY.register("pressure_plate_114", PressurePlate114Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_115 = REGISTRY.register("pressure_plate_115", PressurePlate115Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_116 = REGISTRY.register("pressure_plate_116", PressurePlate116Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_117 = REGISTRY.register("pressure_plate_117", PressurePlate117Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_118 = REGISTRY.register("pressure_plate_118", PressurePlate118Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_119 = REGISTRY.register("pressure_plate_119", PressurePlate119Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_120 = REGISTRY.register("pressure_plate_120", PressurePlate120Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_121 = REGISTRY.register("pressure_plate_121", PressurePlate121Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_122 = REGISTRY.register("pressure_plate_122", PressurePlate122Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_123 = REGISTRY.register("pressure_plate_123", PressurePlate123Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_124 = REGISTRY.register("pressure_plate_124", PressurePlate124Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_125 = REGISTRY.register("pressure_plate_125", PressurePlate125Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_126 = REGISTRY.register("pressure_plate_126", PressurePlate126Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_127 = REGISTRY.register("pressure_plate_127", PressurePlate127Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_128 = REGISTRY.register("pressure_plate_128", PressurePlate128Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_129 = REGISTRY.register("pressure_plate_129", PressurePlate129Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_130 = REGISTRY.register("pressure_plate_130", PressurePlate130Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_131 = REGISTRY.register("pressure_plate_131", PressurePlate131Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_132 = REGISTRY.register("pressure_plate_132", PressurePlate132Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_133 = REGISTRY.register("pressure_plate_133", PressurePlate133Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_134 = REGISTRY.register("pressure_plate_134", PressurePlate134Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_135 = REGISTRY.register("pressure_plate_135", PressurePlate135Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_136 = REGISTRY.register("pressure_plate_136", PressurePlate136Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_137 = REGISTRY.register("pressure_plate_137", PressurePlate137Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_138 = REGISTRY.register("pressure_plate_138", PressurePlate138Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_139 = REGISTRY.register("pressure_plate_139", PressurePlate139Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_140 = REGISTRY.register("pressure_plate_140", PressurePlate140Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_141 = REGISTRY.register("pressure_plate_141", PressurePlate141Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_142 = REGISTRY.register("pressure_plate_142", PressurePlate142Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_143 = REGISTRY.register("pressure_plate_143", PressurePlate143Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_144 = REGISTRY.register("pressure_plate_144", PressurePlate144Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_145 = REGISTRY.register("pressure_plate_145", PressurePlate145Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_146 = REGISTRY.register("pressure_plate_146", PressurePlate146Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_147 = REGISTRY.register("pressure_plate_147", PressurePlate147Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_148 = REGISTRY.register("pressure_plate_148", PressurePlate148Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_149 = REGISTRY.register("pressure_plate_149", PressurePlate149Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_150 = REGISTRY.register("pressure_plate_150", PressurePlate150Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_151 = REGISTRY.register("pressure_plate_151", PressurePlate151Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_152 = REGISTRY.register("pressure_plate_152", PressurePlate152Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_153 = REGISTRY.register("pressure_plate_153", PressurePlate153Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_154 = REGISTRY.register("pressure_plate_154", PressurePlate154Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_155 = REGISTRY.register("pressure_plate_155", PressurePlate155Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_156 = REGISTRY.register("pressure_plate_156", PressurePlate156Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_157 = REGISTRY.register("pressure_plate_157", PressurePlate157Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_158 = REGISTRY.register("pressure_plate_158", PressurePlate158Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_159 = REGISTRY.register("pressure_plate_159", PressurePlate159Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_160 = REGISTRY.register("pressure_plate_160", PressurePlate160Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_161 = REGISTRY.register("pressure_plate_161", PressurePlate161Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_163 = REGISTRY.register("pressure_plate_163", PressurePlate163Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_164 = REGISTRY.register("pressure_plate_164", PressurePlate164Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_165 = REGISTRY.register("pressure_plate_165", PressurePlate165Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_167 = REGISTRY.register("pressure_plate_167", PressurePlate167Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_168 = REGISTRY.register("pressure_plate_168", PressurePlate168Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_169 = REGISTRY.register("pressure_plate_169", PressurePlate169Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_170 = REGISTRY.register("pressure_plate_170", PressurePlate170Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_171 = REGISTRY.register("pressure_plate_171", PressurePlate171Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_172 = REGISTRY.register("pressure_plate_172", PressurePlate172Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_173 = REGISTRY.register("pressure_plate_173", PressurePlate173Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_174 = REGISTRY.register("pressure_plate_174", PressurePlate174Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_175 = REGISTRY.register("pressure_plate_175", PressurePlate175Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_176 = REGISTRY.register("pressure_plate_176", PressurePlate176Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_177 = REGISTRY.register("pressure_plate_177", PressurePlate177Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_178 = REGISTRY.register("pressure_plate_178", PressurePlate178Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_179 = REGISTRY.register("pressure_plate_179", PressurePlate179Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_180 = REGISTRY.register("pressure_plate_180", PressurePlate180Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_181 = REGISTRY.register("pressure_plate_181", PressurePlate181Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_182 = REGISTRY.register("pressure_plate_182", PressurePlate182Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_183 = REGISTRY.register("pressure_plate_183", PressurePlate183Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_184 = REGISTRY.register("pressure_plate_184", PressurePlate184Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_185 = REGISTRY.register("pressure_plate_185", PressurePlate185Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_186 = REGISTRY.register("pressure_plate_186", PressurePlate186Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_187 = REGISTRY.register("pressure_plate_187", PressurePlate187Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_188 = REGISTRY.register("pressure_plate_188", PressurePlate188Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_189 = REGISTRY.register("pressure_plate_189", PressurePlate189Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_190 = REGISTRY.register("pressure_plate_190", PressurePlate190Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_191 = REGISTRY.register("pressure_plate_191", PressurePlate191Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_192 = REGISTRY.register("pressure_plate_192", PressurePlate192Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_193 = REGISTRY.register("pressure_plate_193", PressurePlate193Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_194 = REGISTRY.register("pressure_plate_194", PressurePlate194Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_195 = REGISTRY.register("pressure_plate_195", PressurePlate195Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_196 = REGISTRY.register("pressure_plate_196", PressurePlate196Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_197 = REGISTRY.register("pressure_plate_197", PressurePlate197Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_198 = REGISTRY.register("pressure_plate_198", PressurePlate198Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_199 = REGISTRY.register("pressure_plate_199", PressurePlate199Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_200 = REGISTRY.register("pressure_plate_200", PressurePlate200Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_201 = REGISTRY.register("pressure_plate_201", PressurePlate201Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_202 = REGISTRY.register("pressure_plate_202", PressurePlate202Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_203 = REGISTRY.register("pressure_plate_203", PressurePlate203Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_204 = REGISTRY.register("pressure_plate_204", PressurePlate204Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_205 = REGISTRY.register("pressure_plate_205", PressurePlate205Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_206 = REGISTRY.register("pressure_plate_206", PressurePlate206Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_207 = REGISTRY.register("pressure_plate_207", PressurePlate207Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_208 = REGISTRY.register("pressure_plate_208", PressurePlate208Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_209 = REGISTRY.register("pressure_plate_209", PressurePlate209Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_210 = REGISTRY.register("pressure_plate_210", PressurePlate210Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_211 = REGISTRY.register("pressure_plate_211", PressurePlate211Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_212 = REGISTRY.register("pressure_plate_212", PressurePlate212Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_213 = REGISTRY.register("pressure_plate_213", PressurePlate213Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_214 = REGISTRY.register("pressure_plate_214", PressurePlate214Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_215 = REGISTRY.register("pressure_plate_215", PressurePlate215Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_216 = REGISTRY.register("pressure_plate_216", PressurePlate216Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_217 = REGISTRY.register("pressure_plate_217", PressurePlate217Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_218 = REGISTRY.register("pressure_plate_218", PressurePlate218Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_219 = REGISTRY.register("pressure_plate_219", PressurePlate219Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_220 = REGISTRY.register("pressure_plate_220", PressurePlate220Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_221 = REGISTRY.register("pressure_plate_221", PressurePlate221Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_222 = REGISTRY.register("pressure_plate_222", PressurePlate222Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_223 = REGISTRY.register("pressure_plate_223", PressurePlate223Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_224 = REGISTRY.register("pressure_plate_224", PressurePlate224Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_225 = REGISTRY.register("pressure_plate_225", PressurePlate225Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_226 = REGISTRY.register("pressure_plate_226", PressurePlate226Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_227 = REGISTRY.register("pressure_plate_227", PressurePlate227Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_228 = REGISTRY.register("pressure_plate_228", PressurePlate228Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_229 = REGISTRY.register("pressure_plate_229", PressurePlate229Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_230 = REGISTRY.register("pressure_plate_230", PressurePlate230Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_231 = REGISTRY.register("pressure_plate_231", PressurePlate231Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_232 = REGISTRY.register("pressure_plate_232", PressurePlate232Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_233 = REGISTRY.register("pressure_plate_233", PressurePlate233Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_234 = REGISTRY.register("pressure_plate_234", PressurePlate234Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_235 = REGISTRY.register("pressure_plate_235", PressurePlate235Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_236 = REGISTRY.register("pressure_plate_236", PressurePlate236Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_237 = REGISTRY.register("pressure_plate_237", PressurePlate237Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_238 = REGISTRY.register("pressure_plate_238", PressurePlate238Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_239 = REGISTRY.register("pressure_plate_239", PressurePlate239Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_240 = REGISTRY.register("pressure_plate_240", PressurePlate240Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_241 = REGISTRY.register("pressure_plate_241", PressurePlate241Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_242 = REGISTRY.register("pressure_plate_242", PressurePlate242Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_243 = REGISTRY.register("pressure_plate_243", PressurePlate243Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_244 = REGISTRY.register("pressure_plate_244", PressurePlate244Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_245 = REGISTRY.register("pressure_plate_245", PressurePlate245Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_246 = REGISTRY.register("pressure_plate_246", PressurePlate246Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_247 = REGISTRY.register("pressure_plate_247", PressurePlate247Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_248 = REGISTRY.register("pressure_plate_248", PressurePlate248Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_249 = REGISTRY.register("pressure_plate_249", PressurePlate249Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_250 = REGISTRY.register("pressure_plate_250", PressurePlate250Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_251 = REGISTRY.register("pressure_plate_251", PressurePlate251Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_252 = REGISTRY.register("pressure_plate_252", PressurePlate252Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_253 = REGISTRY.register("pressure_plate_253", PressurePlate253Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_254 = REGISTRY.register("pressure_plate_254", PressurePlate254Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_255 = REGISTRY.register("pressure_plate_255", PressurePlate255Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_256 = REGISTRY.register("pressure_plate_256", PressurePlate256Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_257 = REGISTRY.register("pressure_plate_257", PressurePlate257Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_258 = REGISTRY.register("pressure_plate_258", PressurePlate258Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_259 = REGISTRY.register("pressure_plate_259", PressurePlate259Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_260 = REGISTRY.register("pressure_plate_260", PressurePlate260Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_261 = REGISTRY.register("pressure_plate_261", PressurePlate261Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_262 = REGISTRY.register("pressure_plate_262", PressurePlate262Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_263 = REGISTRY.register("pressure_plate_263", PressurePlate263Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_264 = REGISTRY.register("pressure_plate_264", PressurePlate264Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_265 = REGISTRY.register("pressure_plate_265", PressurePlate265Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_266 = REGISTRY.register("pressure_plate_266", PressurePlate266Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_267 = REGISTRY.register("pressure_plate_267", PressurePlate267Block::new);
	public static final RegistryObject<Block> PRESSURE_PLATE_268 = REGISTRY.register("pressure_plate_268", PressurePlate268Block::new);

	@Mod.EventBusSubscriber(bus = Mod.EventBusSubscriber.Bus.MOD, value = Dist.CLIENT)
	public static class ClientSideHandler {
		@SubscribeEvent
		public static void clientSetup(FMLClientSetupEvent event) {
			GrassPressurePlateBlock.registerRenderLayer();
			DirtPressurePlateBlock.registerRenderLayer();
			CobblestonePressurePlateBlock.registerRenderLayer();
			GranitePressurePlateBlock.registerRenderLayer();
			PolishedGranitePressurePlateBlock.registerRenderLayer();
			DioritePressurePlateBlock.registerRenderLayer();
			PolishedDioritePressurePlateBlock.registerRenderLayer();
			AndesitePressurePlateBlock.registerRenderLayer();
			PolishedAndesitePressurePlateBlock.registerRenderLayer();
			CoarseDirtPressurePlateBlock.registerRenderLayer();
			PodzolPressurePlateBlock.registerRenderLayer();
			CrimsonNyliumPressurePlateBlock.registerRenderLayer();
			WarpedNyliumPressurePlateBlock.registerRenderLayer();
			BedrockPressurePlateBlock.registerRenderLayer();
			SandPressurePlateBlock.registerRenderLayer();
			RedSandPressurePlateBlock.registerRenderLayer();
			GravelPressurePlateBlock.registerRenderLayer();
			GoldOrePressurePlateBlock.registerRenderLayer();
			IronOrePressurePlateBlock.registerRenderLayer();
			CoalOrePressurePlateBlock.registerRenderLayer();
			NetherGoldOrePressurePlateBlock.registerRenderLayer();
			OakLogPressurePlateBlock.registerRenderLayer();
			SpruceLogPressurePlateBlock.registerRenderLayer();
			BirchLogPressurePlateBlock.registerRenderLayer();
			JungleLogPressurePlateBlock.registerRenderLayer();
			AcaciaLogPressurePlateBlock.registerRenderLayer();
			DarkOakLogPressurePlateBlock.registerRenderLayer();
			CrimsonStemPressurePlateBlock.registerRenderLayer();
			WarpedStemPressurePlateBlock.registerRenderLayer();
			PressurePlate18Block.registerRenderLayer();
			PressurePlate19Block.registerRenderLayer();
			PressurePlate20Block.registerRenderLayer();
			PressurePlate21Block.registerRenderLayer();
			PressurePlate22Block.registerRenderLayer();
			PressurePlate23Block.registerRenderLayer();
			PressurePlate24Block.registerRenderLayer();
			PressurePlate25Block.registerRenderLayer();
			PressurePlate26Block.registerRenderLayer();
			PressurePlate27Block.registerRenderLayer();
			PressurePlate28Block.registerRenderLayer();
			PressurePlate29Block.registerRenderLayer();
			PressurePlate30Block.registerRenderLayer();
			PressurePlate31Block.registerRenderLayer();
			PressurePlate32Block.registerRenderLayer();
			PressurePlate33Block.registerRenderLayer();
			PressurePlate34Block.registerRenderLayer();
			PressurePlate35Block.registerRenderLayer();
			PressurePlate36Block.registerRenderLayer();
			PressurePlate37Block.registerRenderLayer();
			PressurePlate38Block.registerRenderLayer();
			PressurePlate39Block.registerRenderLayer();
			PressurePlate40Block.registerRenderLayer();
			PressurePlate41Block.registerRenderLayer();
			PressurePlate42Block.registerRenderLayer();
			PressurePlate43Block.registerRenderLayer();
			PressurePlate44Block.registerRenderLayer();
			PressurePlate45Block.registerRenderLayer();
			PressurePlate46Block.registerRenderLayer();
			PressurePlate47Block.registerRenderLayer();
			PressurePlate48Block.registerRenderLayer();
			PressurePlate49Block.registerRenderLayer();
			PressurePlate50Block.registerRenderLayer();
			PressurePlate51Block.registerRenderLayer();
			PressurePlate52Block.registerRenderLayer();
			PressurePlate53Block.registerRenderLayer();
			PressurePlate54Block.registerRenderLayer();
			PressurePlate55Block.registerRenderLayer();
			PressurePlate56Block.registerRenderLayer();
			PressurePlate57Block.registerRenderLayer();
			PressurePlate58Block.registerRenderLayer();
			PressurePlate59Block.registerRenderLayer();
			PressurePlate60Block.registerRenderLayer();
			PressurePlate61Block.registerRenderLayer();
			PressurePlate62Block.registerRenderLayer();
			PressurePlate63Block.registerRenderLayer();
			PressurePlate64Block.registerRenderLayer();
			PressurePlate65Block.registerRenderLayer();
			PressurePlate67Block.registerRenderLayer();
			PressurePlate68Block.registerRenderLayer();
			PressurePlate69Block.registerRenderLayer();
			PressurePlate70Block.registerRenderLayer();
			PressurePlate71Block.registerRenderLayer();
			PressurePlate72Block.registerRenderLayer();
			PressurePlate73Block.registerRenderLayer();
			PressurePlate74Block.registerRenderLayer();
			PressurePlate75Block.registerRenderLayer();
			PressurePlate76Block.registerRenderLayer();
			PressurePlate77Block.registerRenderLayer();
			PressurePlate78Block.registerRenderLayer();
			PressurePlate79Block.registerRenderLayer();
			PressurePlate80Block.registerRenderLayer();
			PressurePlate81Block.registerRenderLayer();
			PressurePlate82Block.registerRenderLayer();
			PressurePlate83Block.registerRenderLayer();
			PressurePlate84Block.registerRenderLayer();
			PressurePlate85Block.registerRenderLayer();
			PressurePlate86Block.registerRenderLayer();
			PressurePlate87Block.registerRenderLayer();
			PressurePlate88Block.registerRenderLayer();
			PressurePlate89Block.registerRenderLayer();
			PressurePlate90Block.registerRenderLayer();
			PressurePlate91Block.registerRenderLayer();
			PressurePlate92Block.registerRenderLayer();
			PressurePlate93Block.registerRenderLayer();
			PressurePlate94Block.registerRenderLayer();
			PressurePlate95Block.registerRenderLayer();
			PressurePlate96Block.registerRenderLayer();
			PressurePlate97Block.registerRenderLayer();
			PressurePlate98Block.registerRenderLayer();
			PressurePlate99Block.registerRenderLayer();
			PressurePlate100Block.registerRenderLayer();
			PressurePlate101Block.registerRenderLayer();
			PressurePlate102Block.registerRenderLayer();
			PressurePlate103Block.registerRenderLayer();
			PressurePlate104Block.registerRenderLayer();
			PressurePlate105Block.registerRenderLayer();
			PressurePlate106Block.registerRenderLayer();
			PressurePlate107Block.registerRenderLayer();
			PressurePlate108Block.registerRenderLayer();
			PressurePlate109Block.registerRenderLayer();
			PressurePlate110Block.registerRenderLayer();
			PressurePlate111Block.registerRenderLayer();
			PressurePlate112Block.registerRenderLayer();
			PressurePlate113Block.registerRenderLayer();
			PressurePlate114Block.registerRenderLayer();
			PressurePlate115Block.registerRenderLayer();
			PressurePlate116Block.registerRenderLayer();
			PressurePlate117Block.registerRenderLayer();
			PressurePlate118Block.registerRenderLayer();
			PressurePlate119Block.registerRenderLayer();
			PressurePlate120Block.registerRenderLayer();
			PressurePlate121Block.registerRenderLayer();
			PressurePlate122Block.registerRenderLayer();
			PressurePlate123Block.registerRenderLayer();
			PressurePlate124Block.registerRenderLayer();
			PressurePlate125Block.registerRenderLayer();
			PressurePlate126Block.registerRenderLayer();
			PressurePlate127Block.registerRenderLayer();
			PressurePlate128Block.registerRenderLayer();
			PressurePlate129Block.registerRenderLayer();
			PressurePlate130Block.registerRenderLayer();
			PressurePlate131Block.registerRenderLayer();
			PressurePlate132Block.registerRenderLayer();
			PressurePlate133Block.registerRenderLayer();
			PressurePlate134Block.registerRenderLayer();
			PressurePlate135Block.registerRenderLayer();
			PressurePlate136Block.registerRenderLayer();
			PressurePlate137Block.registerRenderLayer();
			PressurePlate138Block.registerRenderLayer();
			PressurePlate139Block.registerRenderLayer();
			PressurePlate140Block.registerRenderLayer();
			PressurePlate141Block.registerRenderLayer();
			PressurePlate142Block.registerRenderLayer();
			PressurePlate143Block.registerRenderLayer();
			PressurePlate144Block.registerRenderLayer();
			PressurePlate145Block.registerRenderLayer();
			PressurePlate146Block.registerRenderLayer();
			PressurePlate147Block.registerRenderLayer();
			PressurePlate148Block.registerRenderLayer();
			PressurePlate149Block.registerRenderLayer();
			PressurePlate150Block.registerRenderLayer();
			PressurePlate151Block.registerRenderLayer();
			PressurePlate152Block.registerRenderLayer();
			PressurePlate153Block.registerRenderLayer();
			PressurePlate154Block.registerRenderLayer();
			PressurePlate155Block.registerRenderLayer();
			PressurePlate156Block.registerRenderLayer();
			PressurePlate157Block.registerRenderLayer();
			PressurePlate158Block.registerRenderLayer();
			PressurePlate159Block.registerRenderLayer();
			PressurePlate160Block.registerRenderLayer();
			PressurePlate161Block.registerRenderLayer();
			PressurePlate163Block.registerRenderLayer();
			PressurePlate164Block.registerRenderLayer();
			PressurePlate165Block.registerRenderLayer();
			PressurePlate167Block.registerRenderLayer();
			PressurePlate168Block.registerRenderLayer();
			PressurePlate169Block.registerRenderLayer();
			PressurePlate170Block.registerRenderLayer();
			PressurePlate171Block.registerRenderLayer();
			PressurePlate172Block.registerRenderLayer();
			PressurePlate173Block.registerRenderLayer();
			PressurePlate174Block.registerRenderLayer();
			PressurePlate175Block.registerRenderLayer();
			PressurePlate176Block.registerRenderLayer();
			PressurePlate177Block.registerRenderLayer();
			PressurePlate178Block.registerRenderLayer();
			PressurePlate179Block.registerRenderLayer();
			PressurePlate180Block.registerRenderLayer();
			PressurePlate181Block.registerRenderLayer();
			PressurePlate182Block.registerRenderLayer();
			PressurePlate183Block.registerRenderLayer();
			PressurePlate184Block.registerRenderLayer();
			PressurePlate185Block.registerRenderLayer();
			PressurePlate186Block.registerRenderLayer();
			PressurePlate187Block.registerRenderLayer();
			PressurePlate188Block.registerRenderLayer();
			PressurePlate189Block.registerRenderLayer();
			PressurePlate190Block.registerRenderLayer();
			PressurePlate191Block.registerRenderLayer();
			PressurePlate192Block.registerRenderLayer();
			PressurePlate193Block.registerRenderLayer();
			PressurePlate194Block.registerRenderLayer();
			PressurePlate195Block.registerRenderLayer();
			PressurePlate196Block.registerRenderLayer();
			PressurePlate197Block.registerRenderLayer();
			PressurePlate198Block.registerRenderLayer();
			PressurePlate199Block.registerRenderLayer();
			PressurePlate200Block.registerRenderLayer();
			PressurePlate201Block.registerRenderLayer();
			PressurePlate202Block.registerRenderLayer();
			PressurePlate203Block.registerRenderLayer();
			PressurePlate204Block.registerRenderLayer();
			PressurePlate205Block.registerRenderLayer();
			PressurePlate206Block.registerRenderLayer();
			PressurePlate207Block.registerRenderLayer();
			PressurePlate208Block.registerRenderLayer();
			PressurePlate209Block.registerRenderLayer();
			PressurePlate210Block.registerRenderLayer();
			PressurePlate211Block.registerRenderLayer();
			PressurePlate212Block.registerRenderLayer();
			PressurePlate213Block.registerRenderLayer();
			PressurePlate214Block.registerRenderLayer();
			PressurePlate215Block.registerRenderLayer();
			PressurePlate216Block.registerRenderLayer();
			PressurePlate217Block.registerRenderLayer();
			PressurePlate218Block.registerRenderLayer();
			PressurePlate219Block.registerRenderLayer();
			PressurePlate220Block.registerRenderLayer();
			PressurePlate221Block.registerRenderLayer();
			PressurePlate222Block.registerRenderLayer();
			PressurePlate223Block.registerRenderLayer();
			PressurePlate224Block.registerRenderLayer();
			PressurePlate225Block.registerRenderLayer();
			PressurePlate226Block.registerRenderLayer();
			PressurePlate227Block.registerRenderLayer();
			PressurePlate228Block.registerRenderLayer();
			PressurePlate229Block.registerRenderLayer();
			PressurePlate230Block.registerRenderLayer();
			PressurePlate231Block.registerRenderLayer();
			PressurePlate232Block.registerRenderLayer();
			PressurePlate233Block.registerRenderLayer();
			PressurePlate234Block.registerRenderLayer();
			PressurePlate235Block.registerRenderLayer();
			PressurePlate236Block.registerRenderLayer();
			PressurePlate237Block.registerRenderLayer();
			PressurePlate238Block.registerRenderLayer();
			PressurePlate239Block.registerRenderLayer();
			PressurePlate240Block.registerRenderLayer();
			PressurePlate241Block.registerRenderLayer();
			PressurePlate242Block.registerRenderLayer();
			PressurePlate243Block.registerRenderLayer();
			PressurePlate244Block.registerRenderLayer();
			PressurePlate245Block.registerRenderLayer();
			PressurePlate246Block.registerRenderLayer();
			PressurePlate247Block.registerRenderLayer();
			PressurePlate248Block.registerRenderLayer();
			PressurePlate249Block.registerRenderLayer();
			PressurePlate250Block.registerRenderLayer();
			PressurePlate251Block.registerRenderLayer();
			PressurePlate252Block.registerRenderLayer();
			PressurePlate253Block.registerRenderLayer();
			PressurePlate254Block.registerRenderLayer();
			PressurePlate255Block.registerRenderLayer();
			PressurePlate256Block.registerRenderLayer();
			PressurePlate257Block.registerRenderLayer();
			PressurePlate258Block.registerRenderLayer();
			PressurePlate259Block.registerRenderLayer();
			PressurePlate260Block.registerRenderLayer();
			PressurePlate261Block.registerRenderLayer();
			PressurePlate262Block.registerRenderLayer();
			PressurePlate263Block.registerRenderLayer();
			PressurePlate264Block.registerRenderLayer();
			PressurePlate265Block.registerRenderLayer();
			PressurePlate266Block.registerRenderLayer();
			PressurePlate267Block.registerRenderLayer();
			PressurePlate268Block.registerRenderLayer();
		}

		@SubscribeEvent
		public static void blockColorLoad(ColorHandlerEvent.Block event) {
			GrassPressurePlateBlock.blockColorLoad(event);
		}
	}
}
